### ISSUE TITLE
 有支持1.12.2的计划吗?

### ISSUE THREAD

**Issue by 1cyberlangke1** [ViaVersionMCP/ViaForgePlus#11]
如题, 1.12可以用副手

**Comment by hsuchenghao** [comment]
此mod的作者为日本人，你应该使用英文或者日语请求issue
The author of this mod is Japanese, you should request the issue in English or Japanese.

**Comment by 1cyberlangke1** [comment]
> 此mod的作者为日本人，你应该使用英文或者日语请求issue The author of this mod is Japanese, you should request the issue in English or Japanese.

ok
